# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a993fb781749458e13dbb2180c580c0620f964794083062a690ce2d907b7a1eb3fd564cb196f10f758de8ee5fd601ff76bda063de3a2a4d00fd89cedb3b56ea

test:
  secret_key_base: 74fbeacd6455218bb2c0be9904c23a2745571b6452e48387ee5c7ed327e4ee0ee0848ff82fd6ff3559db4c7f0cb56ac800c2b18ca507149648d6535ebf4e88b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
